// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZliFl99alLS1rQKmK2pahjSHKZ8AlMAo',
    appId: '1:746981175271:web:38bc75bdcb80195d301742',
    messagingSenderId: '746981175271',
    projectId: 'pushcalls',
    authDomain: 'pushcalls.firebaseapp.com',
    storageBucket: 'pushcalls.firebasestorage.app',
    measurementId: 'G-JBXB7EHHNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSHCAAqsC-NEKs9cwDfCqgxcPCc1-Lp-s',
    appId: '1:746981175271:android:c73bde9d5e491452301742',
    messagingSenderId: '746981175271',
    projectId: 'pushcalls',
    storageBucket: 'pushcalls.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3GeCeWo3_txvyHCYCXMoku6y3mjylu9M',
    appId: '1:746981175271:ios:1b6bbadcacbdeddb301742',
    messagingSenderId: '746981175271',
    projectId: 'pushcalls',
    storageBucket: 'pushcalls.firebasestorage.app',
    iosBundleId: 'com.example.whisper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3GeCeWo3_txvyHCYCXMoku6y3mjylu9M',
    appId: '1:746981175271:ios:1b6bbadcacbdeddb301742',
    messagingSenderId: '746981175271',
    projectId: 'pushcalls',
    storageBucket: 'pushcalls.firebasestorage.app',
    iosBundleId: 'com.example.whisper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZliFl99alLS1rQKmK2pahjSHKZ8AlMAo',
    appId: '1:746981175271:web:3b1e01f2995e9c74301742',
    messagingSenderId: '746981175271',
    projectId: 'pushcalls',
    authDomain: 'pushcalls.firebaseapp.com',
    storageBucket: 'pushcalls.firebasestorage.app',
    measurementId: 'G-G82JC5ZXVZ',
  );
}
